name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalación de dependencias
        run: npm install

      - name: Construir proyecto (Build)
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto para el Deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # SvelteKit genera esta carpeta

      - name: Publicación automática (Deploy)
        id: deployment
        uses: actions/deploy-pages@v4